import { ProductFocusProvider } from "@/providers/ProductFocusContext";
import { SidebarProvider } from "@/providers/SidebarContext";
import TopLoaderProvider from "@/providers/TopLoaderProvider";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";


const dm_sans = DM_Sans({
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin"],
	variable: "--font-dm-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${dm_sans.variable} ${dm_sans.className}`}>
				<SidebarProvider>
						<ProductFocusProvider>
								<TopLoaderProvider>{children}</TopLoaderProvider>
						</ProductFocusProvider>
				</SidebarProvider>
				<ToastContainer
					position="bottom-right"
					pauseOnHover={false}
					closeOnClick
					toastClassName="rounded-full"
				/>
			</body>
		</html>
	);
}
